// Ship only icons referenced by the static prototype, with no CDN dependency.
const fs = require('node:fs');
const path = require('node:path');
const { icons } = require('lucide');
const root = path.resolve(__dirname, '..');
const source = ['index.html', 'app.js', 'calm.js'].map(file => fs.readFileSync(path.join(root, file), 'utf8')).join('\n');
const kebab = name => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([a-zA-Z])(\d+)/g, '$1-$2').toLowerCase();
const selected = Object.fromEntries(Object.entries(icons).map(([name, data]) => [kebab(name), data]).filter(([name]) => source.includes(name)));
const runtime = `/* Lucide ${require('lucide/package.json').version}; ISC license in lucide-LICENSE. Generated by npm run build:icons. */
(()=>{const icons=${JSON.stringify(selected)};window.lucide={createIcons(){document.querySelectorAll('i[data-lucide]').forEach(old=>{const name=old.getAttribute('data-lucide'),nodes=icons[name];if(!nodes){console.warn('Missing icon: '+name);return;}const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');Object.entries({width:24,height:24,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor','stroke-width':2,'stroke-linecap':'round','stroke-linejoin':'round','aria-hidden':'true',focusable:'false'}).forEach(([key,value])=>svg.setAttribute(key,value));for(const attr of old.attributes)svg.setAttribute(attr.name,attr.value);svg.setAttribute('class',('lucide lucide-'+name+' '+(old.getAttribute('class')||'')).trim());for(const [tag,attrs] of nodes){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value] of Object.entries(attrs))el.setAttribute(key,value);svg.append(el);}old.replaceWith(svg);});}}})();
`;
fs.mkdirSync(path.join(root, 'vendor'), { recursive: true });
fs.writeFileSync(path.join(root, 'vendor/lucide.min.js'), runtime);
fs.copyFileSync(path.join(root, 'node_modules/lucide/LICENSE'), path.join(root, 'vendor/lucide-LICENSE'));
console.log(`Generated ${Object.keys(selected).length} local icons (${Buffer.byteLength(runtime)} bytes).`);
